In [58]:
import numpy as np
import time

In [59]:
a = np.zeros(4)
print(f"np.zeros(4) : a={a},a.shape={a.shape},dataType={a.dtype}")
a = np.zeros((4))
print(f"np.zeros(4) : a={a},a.shape={a.shape},dataType={a.dtype}")
a = np.random.random_sample(4)
print(f"np.zeros(4) : a={a},a.shape={a.shape},dataType={a.dtype}")


np.zeros(4) : a=[0. 0. 0. 0.],a.shape=(4,),dataType=float64
np.zeros(4) : a=[0. 0. 0. 0.],a.shape=(4,),dataType=float64
np.zeros(4) : a=[0.5669563  0.36607953 0.12254939 0.41590761],a.shape=(4,),dataType=float64


In [60]:
a = np.arange(4)
print(f"a={a},a.shape={a.shape}")

print(f'a[2]={a[2]},a[2].shape={a[2].shape}')

print(f"a[-1]={a[-1]}")

a=[0 1 2 3],a.shape=(4,)
a[2]=2,a[2].shape=()
a[-1]=3


In [61]:
try:
    c = a[10]
except Exception as e:
    print("ERROR:")
    print(e)

ERROR:
index 10 is out of bounds for axis 0 with size 4


In [62]:
a = np.arange(10)
print(f"a={a}")
c = a[2:7:1]
print(f"a[2:7:1]={c}")
c = a[3:]
print(f"a[3:]={c}")

c = a[:3]
print(f"a[:3]={c}")

c = a[:]
print(f"a[:]={c}")



a=[0 1 2 3 4 5 6 7 8 9]
a[2:7:1]=[2 3 4 5 6]
a[3:]=[3 4 5 6 7 8 9]
a[:3]=[0 1 2]
a[:]=[0 1 2 3 4 5 6 7 8 9]


In [63]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"a={a}")

print(f"-a={-a}")

print(f"np.sum(a)={np.sum(a)}")

print(f"np.mean(a)={np.mean(a)}")

print(f"a**2={a ** 2}")


a=[ 1  2  3  4  5  6  7  8  9 10]
-a=[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]
np.sum(a)=55
np.mean(a)=5.5
a**2=[  1   4   9  16  25  36  49  64  81 100]


In [64]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])
print(a + b)

[0 0 6 8]


In [65]:
c = np.array([1, 2])

# print(a+c)
print(5 * a)

[ 5 10 15 20]


In [66]:
def my_dot(a, b):
    x = 0
    for i in range(a.shape[0]):
        x += (a[i] * b[i])
    return x

In [67]:
a = np.array([0, 0, 1, 2])
b = np.array([-1, -2, -3, -4])
my_dot(a, b)

-11

In [68]:
np.dot(a, b), np.dot(b, a)

(-11, -11)

In [69]:
np.random.seed(1)

a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(f"np.dot(a,b)={c:.2f}")
print(f"Vectorized version duration：{1000 * (toc - tic):.2f}")

tic = time.time()
c = my_dot(a, b)
toc = time.time()
print(f"my_dot(a,b)={c:.2f}")
print(f"loop version duration：{1000 * (toc - tic):.2f}")

del (a)
del (b)


np.dot(a,b)=2501072.58
Vectorized version duration：6.97
my_dot(a,b)=2501072.58
loop version duration：3442.61


In [70]:
X = np.arange(1, 13, 1).reshape(4, 3)
w = np.ones(3) * 2
c = np.dot(X[2], w)
c


48.0

In [71]:
a = np.zeros((1, 5))
print(f"a={a},a.shape={a.shape}")

a = np.zeros((2, 5))
print(f"a={a},a.shape={a.shape}")

a = np.random.random_sample((4, 5))
print(f"a={a},a.shape={a.shape}")


a=[[0. 0. 0. 0. 0.]],a.shape=(1, 5)
a=[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]],a.shape=(2, 5)
a=[[0.44236513 0.04997798 0.77390955 0.93782363 0.5792328 ]
 [0.53516563 0.80204309 0.24814448 0.59096694 0.32950282]
 [0.98797985 0.86846315 0.16452144 0.80277814 0.02503441]
 [0.89766393 0.41783454 0.53671084 0.19721356 0.26810967]],a.shape=(4, 5)


In [72]:
a = np.arange(6).reshape(-1, 2)
print(f"a.shape:{a.shape}\n a={a}\n")


a.shape:(3, 2)
 a=[[0 1]
 [2 3]
 [4 5]]


In [73]:
print(f'a[2]={a[2]},\n'
      f'a[2].shape={a[2].shape}\n'
      f'type(a[2])={type(a[2])}\n')
print(f'a[2.0]={a[2,0]},\n'
      f'a[2.0].shape={a[2,0].shape}\n'
      f'type(a[2.0])={type(a[2,0])}\n')

a[2]=[4 5],
a[2].shape=(2,)
type(a[2])=<class 'numpy.ndarray'>

a[2.0]=4,
a[2.0].shape=()
type(a[2.0])=<class 'numpy.int32'>


In [75]:
a=np.arange(20,dtype=np.float32).reshape(-1,10)
print(f"a=\n{a}")

print(f"a[0,2:7:1]={a[0,2:7:1]}")
print(f"a[0,2:7:1].shape={a[0,2:7:1].shape}")

a=
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
a[0,2:7:1]=[2. 3. 4. 5. 6.]
a[0,2:7:1].shape=(5,)


In [77]:
print(f"a[:,2:7:1]=\n{a[:,2:7:1]}")
print(f"a[:,2:7:1].shape={a[:,2:7:1].shape}")

a[:,2:7:1]=
[[ 2.  3.  4.  5.  6.]
 [12. 13. 14. 15. 16.]]
a[:,2:7:1].shape=(2, 5)


In [79]:
print(f"a[:,:]=\n{a[:,:]}")
print(f"a[:,:].shape={a[:,:].shape}")

a[:,:]=
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
a[:,:].shape=(2, 10)


In [81]:
print(f"a[1,:]=\n{a[1,:]}")
print(f"a[1,:].shape={a[1,:].shape}")

a[1,:]=
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
a[1,:].shape=(10,)


In [82]:
print(f"a[1]=\n{a[1]}")
print(f"a[1].shape={a[1].shape}")

a[1]=
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
a[1].shape=(10,)
