# 可选实验室：Python、NumPy 和矢量化
简要介绍本课程中使用的一些科学计算。特别是 NumPy 科学计算包及其与 python 的使用。

# 大纲
- [  1.1 目标](#toc_40015_1.1)
- [  1.2 有用的参考资料](#toc_40015_1.2)
- [2 Python 和 NumPy <a name='Python 和 NumPy'></a>](#toc_40015_2)
- [3 个向量](#toc_40015_3)
- [  3.1 摘要](#toc_40015_3.1)
- [  3.2 NumPy 数组](#toc_40015_3.2)
- [  3.3 矢量创建](#toc_40015_3.3)
- [  3.4 向量运算](#toc_40015_3.4)
- [4 个矩阵](#toc_40015_4)
- [  4.1 摘要](#toc_40015_4.1)
- [  4.2 NumPy 数组](#toc_40015_4.2)
- [  4.3 矩阵创建](#toc_40015_4.3)
- [  4.4 矩阵运算](#toc_40015_4.4)

# 可选实验室：Python、NumPy 和矢量化
简要介绍本课程中使用的一些科学计算。特别是 NumPy 科学计算包及其与 python 的使用。

# 大纲
- [  1.1 目标](#toc_40015_1.1)
- [  1.2 有用的参考资料](#toc_40015_1.2)
- [2 Python 和 NumPy <a name='Python and NumPy'></a>](#toc_40015_2)
- [3 个向量](#toc_40015_3)
- [  3.1 摘要](#toc_40015_3.1)
- [  3.2 NumPy 数组](#toc_40015_3.2)
- [  3.3 矢量创建](#toc_40015_3.3)
- [  3.4 向量运算](#toc_40015_3.4)
- [4 个矩阵](#toc_40015_4)
- [  4.1 摘要](#toc_40015_4.1)
- [  4.2 NumPy 数组](#toc_40015_4.2)
- [  4.3 矩阵创建](#toc_40015_4.3)
- [  4.4 矩阵运算](#toc_40015_4.4)

In [1]:
import numpy as np  # it is an unofficial standard to use np for numpy
import time


<a name="toc_40015_1.1"></a>
## 1.1 Goals
In this lab, you will:
- Review the features of NumPy and Python that are used in Course 1

<a name="toc_40015_1.1"></a>
## 1.1 目标
在本实验室中，您将：
- 回顾课程 1 中使用的 NumPy 和 Python 的功能

<a name="toc_40015_1.2"></a>
## 1.2 Useful References
- NumPy Documentation including a basic introduction: [NumPy.org](https://NumPy.org/doc/stable/)
- A challenging feature topic: [NumPy Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)


<a name="toc_40015_1.2"></a>
## 1.2 有用的参考资料
- NumPy 文档，包括基本介绍：[NumPy.org](https://NumPy.org/doc/stable/)
- 一个具有挑战性的功能主题：[NumPy Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)

<a name="toc_40015_2"></a>
# 2 Python and NumPy <a name='Python and NumPy'></a>
Python is the programming language we will be using in this course. It has a set of numeric data types and arithmetic operations. NumPy is a library that extends the base capabilities of python to add a richer data set including more numeric types, vectors, matrices, and many matrix functions. NumPy and python  work together fairly seamlessly. Python arithmetic operators work on NumPy data types and many NumPy functions will accept python data types.


<a name="toc_40015_2"></a>
# 2 Python 和 NumPy <a name='Python and NumPy'></a>
Python 是我们将在本课程中使用的编程语言。它具有一组数字数据类型和算术运算。 NumPy 是一个扩展 Python 基本功能的库，可添加更丰富的数据集，包括更多数值类型、向量、矩阵和许多矩阵函数。 NumPy 和 python 可以相当无缝地协同工作。 Python 算术运算符适用于 NumPy 数据类型，并且许多 NumPy 函数将接受 Python 数据类型。

<a name="toc_40015_3"></a>
# 3 Vectors
<a name="toc_40015_3.1"></a>
## 3.1 Abstract
<img align="right" src="./images/C1_W2_Lab04_Vectors.PNG" style="width:340px;" >Vectors, as you will use them in this course, are ordered arrays of numbers. In notation, vectors are denoted with lower case bold letters such as $\mathbf{x}$.  The elements of a vector are all the same type. A vector does not, for example, contain both characters and numbers. The number of elements in the array is often referred to as the *dimension* though mathematicians may prefer *rank*. The vector shown has a dimension of $n$. The elements of a vector can be referenced with an index. In math settings, indexes typically run from 1 to n. In computer science and these labs, indexing will typically run from 0 to n-1.  In notation, elements of a vector, when referenced individually will indicate the index in a subscript, for example, the $0^{th}$ element, of the vector $\mathbf{x}$ is $x_0$. Note, the x is not bold in this case.  


<a name="toc_40015_3"></a>
# 3 向量
<a name="toc_40015_3.1"></a>
## 3.1 摘要
<img align="right" src="./images/C1_W2_Lab04_Vectors.PNG" style="width:340px;" >正如您将在本课程中使用的那样，向量是有序的数字数组。在符号中，向量用小写粗体字母表示，例如 $\mathbf{x}$。向量的元素都是同一类型。例如，向量并不同时包含字符和数字。数组中元素的数量通常被称为*维度*，尽管数学家可能更喜欢*rank*。所示向量的维度为 $n$。向量的元素可以通过索引来引用。在数学设置中，索引通常从 1 到 n。在计算机科学和这些实验室中，索引通常从 0 到 n-1。在符号中，向量的元素在单独引用时将指示下标中的索引，例如向量 $\mathbf{x}$ 的 $0^{th}$ 元素是 $x_0$。请注意，在这种情况下 x 不是粗体。

<a name="toc_40015_3.2"></a>
## 3.2 NumPy Arrays

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). Right away, you may notice we have overloaded the term 'dimension'. Above, it was the number of elements in the vector, here, dimension refers to the number of indexes of an array. A one-dimensional or 1-D array has one index. In Course 1, we will represent vectors as NumPy 1-D arrays. 

 - 1-D array, shape (n,): n elements indexed [0] through [n-1]
 

<a name="toc_40015_3.2"></a>
## 3.2 NumPy 数组

NumPy 的基本数据结构是一个可索引的 n 维*数组*，包含相同类型（`dtype`）的元素。您可能马上就会注意到我们已经超载了“维度”这个术语。上面，它是向量中元素的数量，这里，维度指的是数组的索引数量。一维或一维数组有一个索引。在课程 1 中，我们将把向量表示为 NumPy 一维数组。

 - 一维数组，形状 (n,)：索引为 [0] 到 [n-1] 的 n 个元素

<a name="toc_40015_3.3"></a>
## 3.3 Vector Creation


<a name="toc_40015_3.3"></a>
## 3.3 向量创建

Data creation routines in NumPy will generally have a first parameter which is the shape of the object. This can either be a single value for a 1-D result or a tuple (n,m,...) specifying the shape of the result. Below are examples of creating vectors using these routines.

NumPy 中的数据创建例程通常有第一个参数，即对象的形状。这可以是一维结果的单个值，也可以是指定结果形状的元组 (n,m,...)。以下是使用这些例程创建向量的示例。

In [2]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4)
print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,))
print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4);
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.8424196  0.17279034 0.34443403 0.00988865], a shape = (4,), a data type = float64


Some data creation routines do not take a shape tuple:

一些数据创建例程不采用形状元组：

In [3]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);
print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.23215399 0.55992725 0.10631303 0.96786583], a shape = (4,), a data type = float64


values can be specified manually as well. 

In [4]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5, 4, 3, 2]);
print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5., 4, 3, 2]);
print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int32
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


These have all created a one-dimensional vector  `a` with four elements. `a.shape` returns the dimensions. Here we see a.shape = `(4,)` indicating a 1-d array with 4 elements.  

<a name="toc_40015_3.4"></a>
## 3.4 Operations on Vectors
Let's explore some operations using vectors.
<a name="toc_40015_3.4.1"></a>
### 3.4.1 Indexing
Elements of vectors can be accessed via indexing and slicing. NumPy provides a very complete set of indexing and slicing capabilities. We will explore only the basics needed for the course here. Reference [Slicing and Indexing](https://NumPy.org/doc/stable/reference/arrays.indexing.html) for more details.  
**Indexing** means referring to *an element* of an array by its position within the array.  
**Slicing** means getting a *subset* of elements from an array based on their indices.  
NumPy starts indexing at zero so the 3rd element of an vector $\mathbf{a}$ is `a[2]`.

<a name="toc_40015_3.4"></a>
## 3.4 向量运算
让我们探索一些使用向量的操作。
<a name="toc_40015_3.4.1"></a>
### 3.4.1 索引
向量的元素可以通过索引和切片来访问。 NumPy 提供了一套非常完整的索引和切片功能。我们将仅探讨本课程所需的基础知识。有关更多详细信息，请参阅[切片和索引](https://NumPy.org/doc/stable/reference/arrays.indexing.html)。
**索引**意味着通过数组中的位置来引用数组的*元素*。
**切片** 意味着根据索引从数组中获取元素的*子集*。
NumPy 从零开始索引，因此向量 $\mathbf{a}$ 的第三个元素是“a[2]”。

In [5]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


<a name="toc_40015_3.4.2"></a>
### 3.4.2 Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

<a name="toc_40015_3.4.2"></a>
### 3.4.2 切片
切片使用一组三个值（“start:stop:step”）创建一个索引数组。值的子集也是有效的。它的使用最好通过示例来解释：

In [6]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];
print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];
print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];
print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];
print("a[:3]    = ", c)

# access all elements
c = a[:];
print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


<a name="toc_40015_3.4.3"></a>
### 3.4.3 Single vector operations
There are a number of useful operations that involve operations on a single vector.

<a name="toc_40015_3.4.3"></a>
### 3.4.3 单向量运算
有许多有用的操作涉及对单个向量的操作。

In [7]:
a = np.array([1, 2, 3, 4])
print(f"a             : {a}")
# negate elements of a
b = -a
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a)
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a ** 2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


<a name="toc_40015_3.4.4"></a>
### 3.4.4 Vector Vector element-wise operations
Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well. These operators work on an element-by-element basis. For example 
$$ \mathbf{a} + \mathbf{b} = \sum_{i=0}^{n-1} a_i + b_i $$

<a name="toc_40015_3.4.4"></a>
### 3.4.4 向量向量逐元素运算
大多数 NumPy 算术、逻辑和比较运算也适用于向量。这些运算符在逐个元素的基础上工作。例如
数学1

In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


Of course, for this to work correctly, the vectors must be of the same size:

当然，为了使其正常工作，向量必须具有相同的大小：

In [9]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


<a name="toc_40015_3.4.5"></a>
### 3.4.5 Scalar Vector operations
Vectors can be 'scaled' by scalar values. A scalar value is just a number. The scalar multiplies all the elements of the vector.

<a name="toc_40015_3.4.5"></a>
### 3.4.5 标量向量运算
向量可以按标量值“缩放”。标量值只是一个数字。标量乘以向量的所有元素。

In [10]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


<a name="toc_40015_3.4.6"></a>
### 3.4.6 Vector Vector dot product
The dot product is a mainstay of Linear Algebra and NumPy. This is an operation used extensively in this course and should be well understood. The dot product is shown below.

<a name="toc_40015_3.4.6"></a>
### 3.4.6 向量向量点积
点积是线性代数和 NumPy 的支柱。这是本课程中广泛使用的操作，应该很好理解。点积如下所示。

<img src="./images/C1_W2_Lab04_dot_notrans.gif" width=800> 

The dot product multiplies the values in two vectors element-wise and then sums the result.
Vector dot product requires the dimensions of the two vectors to be the same. 

点积将两个向量中的值按元素相乘，然后将结果相加。
向量点积要求两个向量的维度相同。

Let's implement our own version of the dot product below:

**Using a for loop**, implement a function which returns the dot product of two vectors. The function to return given inputs $a$ and $b$:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Assume both `a` and `b` are the same shape.

让我们实现下面我们自己的点积版本：

**使用 for 循环**，实现一个返回两个向量的点积的函数。返回给定输入 $a$ 和 $b$ 的函数：
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
假设“a”和“b”是相同的形状。

In [11]:
def my_dot(a, b):
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [12]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


Note, the dot product is expected to return a scalar value. 

Let's try the same operations using `np.dot`.  

请注意，点积预计返回标量值。

让我们使用“np.dot”尝试相同的操作。

In [13]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ")
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


Above, you will note that the results for 1-D matched our implementation.

在上面，您会注意到一维的结果与我们的实现相匹配。

<a name="toc_40015_3.4.7"></a>
### 3.4.7 The Need for Speed: vector vs for loop
We utilized the NumPy  library because it improves speed memory efficiency. Let's demonstrate:

<a name="toc_40015_3.4.7"></a>
### 3.4.7 极品速度：向量与 for 循环
我们使用 NumPy 库是因为它提高了速度内存效率。我们来演示一下：

In [14]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000 * (toc - tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a, b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000 * (toc - tic):.4f} ms ")

del (a);
del (b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 8.9731 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 3930.5291 ms 


So, vectorization provides a large speed up in this example. This is because NumPy makes better use of available data parallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in Machine Learning where the data sets are often very large.

因此，矢量化在此示例中提供了很大的加速。这是因为 NumPy 更好地利用了底层硬件中的可用数据并行性。 GPU 和现代 CPU 实现单指令、多数据 (SIMD) 管道，允许并行发出多个操作。这在机器学习中至关重要，因为数据集通常非常大。

<a name="toc_12345_3.4.8"></a>
### 3.4.8 Vector Vector operations in Course 1
Vector Vector operations will appear frequently in course 1. Here is why:
- Going forward, our examples will be stored in an array, `X_train` of dimension (m,n). This will be explained more in context, but here it is important to note it is a 2 Dimensional array or matrix (see next section on matrices).
- `w` will be a 1-dimensional vector of shape (n,).
- we will perform operations by looping through the examples, extracting each example to work on individually by indexing X. For example:`X[i]`
- `X[i]` returns a value of shape (n,), a 1-dimensional vector. Consequently, operations involving `X[i]` are often vector-vector.  

That is a somewhat lengthy explanation, but aligning and understanding the shapes of your operands is important when performing vector operations.

<a name="toc_12345_3.4.8"></a>
### 3.4.8 向量 课程 1 中的向量运算
Vector 向量运算在课程1中会频繁出现，原因如下：
- 展望未来，我们的示例将存储在维度为 (m,n) 的数组“X_train”中。这将在上下文中进行更多解释，但这里重要的是要注意它是一个二维数组或矩阵（请参阅下一节有关矩阵的内容）。
- `w` 将是形状为 (n,) 的一维向量。
- 我们将通过循环示例来执行操作，通过索引 X 提取每个示例以单独处理。例如：`X[i]`
- `X[i]` 返回形状 (n,) 的值，一个一维向量。因此，涉及“X[i]”的运算通常是向量-向量。

这是一个有点冗长的解释，但是在执行向量运算时，对齐和理解操作数的形状非常重要。

In [15]:
# show common Course 1 example
X = np.array([[1], [2], [3], [4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


<a name="toc_40015_4"></a>
# 4 Matrices


<a name="toc_40015_4"></a>
# 4 矩阵

<a name="toc_40015_4.1"></a>
## 4.1 Abstract
Matrices, are two dimensional arrays. The elements of a matrix are all of the same type. In notation, matrices are denoted with capitol, bold letter such as $\mathbf{X}$. In this and other labs, `m` is often the number of rows and `n` the number of columns. The elements of a matrix can be referenced with a two dimensional index. In math settings, numbers in the index typically run from 1 to n. In computer science and these labs, indexing will run from 0 to n-1.  
<figure>
    <center> <img src="./images/C1_W2_Lab04_Matrices.PNG"  alt='missing'  width=900><center/>
    <figcaption> Generic Matrix Notation, 1st index is row, 2nd is column </figcaption>
<figure/>

<a name="toc_40015_4.1"></a>
## 4.1 摘要
矩阵，是二维数组。矩阵的元素都是同一类型。在表示法中，矩阵用大写字母、粗体字母表示，例如 $\mathbf{X}$。在本实验和其他实验中，“m”通常是行数，“n”是列数。矩阵的元素可以用二维索引来引用。在数学设置中，索引中的数字通常从 1 到 n。在计算机科学和这些实验室中，索引将从 0 到 n-1。
<figure>
    <center> <img src="./images/C1_W2_Lab04_Matrices.PNG"  alt='missing'  width=900><center/>
    <figcaption> 通用矩阵表示法，第一个索引是行，第二个索引是列 </figcaption>
<figure/>

<a name="toc_40015_4.2"></a>
## 4.2 NumPy Arrays

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). These were described earlier. Matrices have a two-dimensional (2-D) index [m,n].

In Course 1, 2-D matrices are used to hold training data. Training data is $m$ examples by $n$ features creating an (m,n) array. Course 1 does not do operations directly on matrices but typically extracts an example as a vector and operates on that. Below you will review: 
- data creation
- slicing and indexing

<a name="toc_40015_4.2"></a>
## 4.2 NumPy 数组

NumPy 的基本数据结构是一个可索引的 n 维*数组*，包含相同类型（`dtype`）的元素。这些已在前面描述过。矩阵具有二维 (2-D) 索引 [m,n]。

在课程 1 中，二维矩阵用于保存训练数据。训练数据是 $m$ 示例，由 $n$ 功能创建 (m,n) 数组。课程 1 不会直接对矩阵进行运算，而是通常提取一个示例作为向量并对其进行运算。下面您将回顾：
- 数据创建
- 切片和索引

<a name="toc_40015_4.3"></a>
## 4.3 Matrix Creation
The same functions that created 1-D vectors will create 2-D or n-D arrays. Here are some examples


<a name="toc_40015_4.3"></a>
## 4.3 矩阵创建
创建一维向量的相同函数将创建二维或 n 维数组。这里有些例子

Below, the shape tuple is provided to achieve a 2-D result. Notice how NumPy uses brackets to denote each dimension. Notice further than NumPy, when printing, will print one row per line.


下面提供了形状元组来实现二维结果。请注意 NumPy 如何使用括号来表示每个维度。请注意，NumPy 在打印时将每行打印一行。

In [16]:
a = np.zeros((1, 5))
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((2, 1))
print(f"a shape = {a.shape}, a = {a}")

a = np.random.random_sample((1, 1))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


One can also manually specify data. Dimensions are specified with additional brackets matching the format in the printing above.

也可以手动指定数据。尺寸用与上面印刷中的格式匹配的附加括号指定。

In [17]:
# NumPy's routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);
print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],  # One can also
              [4],  # separate values
              [3]]);  #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


<a name="toc_40015_4.4"></a>
## 4.4 Operations on Matrices
Let's explore some operations using matrices.

<a name="toc_40015_4.4"></a>
## 4.4 矩阵运算
让我们探索一些使用矩阵的运算。

<a name="toc_40015_4.4.1"></a>
### 4.4.1 Indexing


<a name="toc_40015_4.4.1"></a>
### 4.4.1 索引

Matrices include a second index. The two indexes describe [row, column]. Access can either return an element or a row/column. See below:

矩阵包括第二个索引。这两个索引描述的是[行，列]。访问可以返回一个元素或行/列。见下文：

In [18]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)  #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(
    f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int32'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


It is worth drawing attention to the last example. Accessing a matrix by just specifying the row will return a *1-D vector*.

值得注意的是最后一个例子。仅通过指定行来访问矩阵将返回*一维向量*。

**Reshape**  
The previous example used [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) to shape the array.  
`a = np.arange(6).reshape(-1, 2) `   
This line of code first created a *1-D Vector* of six elements. It then reshaped that vector into a *2-D* array using the reshape command. This could have been written:  
`a = np.arange(6).reshape(3, 2) `  
To arrive at the same 3 row, 2 column array.
The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.


**重塑**

前面的示例使用 [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) 来调整数组的形状。
`a = np.arange(6).reshape(-1, 2) `
这行代码首先创建了一个包含六个元素的 *1-D Vector*。然后，它使用 reshape 命令将该向量重塑为 *2-D* 数组。这可以写成：
`a = np.arange(6).reshape(3, 2) `
得到同样的3行2列数组。
-1 参数告诉例程在给定数组大小和列数的情况下计算行数。

<a name="toc_40015_4.4.2"></a>
### 4.4.2 Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

<a name="toc_40015_4.4.2"></a>
### 4.4.2 切片
切片使用一组三个值（“start:stop:step”）创建一个索引数组。值的子集也是有效的。它的使用最好通过示例来解释：

In [19]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:, :], ",  a[:,:].shape =", a[:, :].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1, :], ",  a[1,:].shape =", a[1, :].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1], ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


<a name="toc_40015_5.0"></a>
## Congratulations!
In this lab you mastered the features of Python and NumPy that are needed for Course 1.

<a name="toc_40015_5.0"></a>
## 恭喜！
在本实验中，您掌握了课程 1 所需的 Python 和 NumPy 功能。